/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TimeSheetImport } from './routes/TimeSheet'
import { Route as ProfileImport } from './routes/Profile'
import { Route as MainImport } from './routes/Main'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TimeSheetRoute = TimeSheetImport.update({
  id: '/TimeSheet',
  path: '/TimeSheet',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/Profile',
  path: '/Profile',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  id: '/Main',
  path: '/Main',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Main': {
      id: '/Main'
      path: '/Main'
      fullPath: '/Main'
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/Profile': {
      id: '/Profile'
      path: '/Profile'
      fullPath: '/Profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/TimeSheet': {
      id: '/TimeSheet'
      path: '/TimeSheet'
      fullPath: '/TimeSheet'
      preLoaderRoute: typeof TimeSheetImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Main': typeof MainRoute
  '/Profile': typeof ProfileRoute
  '/TimeSheet': typeof TimeSheetRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Main': typeof MainRoute
  '/Profile': typeof ProfileRoute
  '/TimeSheet': typeof TimeSheetRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Main': typeof MainRoute
  '/Profile': typeof ProfileRoute
  '/TimeSheet': typeof TimeSheetRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Main' | '/Profile' | '/TimeSheet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Main' | '/Profile' | '/TimeSheet'
  id: '__root__' | '/' | '/Main' | '/Profile' | '/TimeSheet'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRoute
  ProfileRoute: typeof ProfileRoute
  TimeSheetRoute: typeof TimeSheetRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRoute,
  ProfileRoute: ProfileRoute,
  TimeSheetRoute: TimeSheetRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Main",
        "/Profile",
        "/TimeSheet"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Main": {
      "filePath": "Main.tsx"
    },
    "/Profile": {
      "filePath": "Profile.tsx"
    },
    "/TimeSheet": {
      "filePath": "TimeSheet.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
